### PR TITLE
Add lesson with long footnotes (with paragraphs)

### PR DESCRIPTION
**Pull request by eudoxos**
Hi, I am not sure how much (if at all) are footnotes containing paragraphs specified by the standard. The examples I have seen are all simple spans. In real books, especially scholarly works, commented translations etc, footnotes with many paragraphs are commonplace  (There are some real-world examples of such footnotes in https://eudoxos.github.io/vism/ which is rendered in several different ways.). What I could test (WeasyPrint and Vivliostyle), they are not rendered correctly. I used the `<span class="footnote"><p>...</p></span>` syntax.

I would welcome this feature to be documented as a lesson (perhaps figuring out the correct syntax).

### CODE REVIEW

**Comment by eudoxos** [comment]
I changed from `<span ...>` to `<div ...>`, it works somewhat better, but with issues (WeasyPrint and Vivliostyle tested)

**Comment by MurakamiShinyu** [comment]
HTML `<p>` element cannot have `<div>` elements inside. So the `<p>...<div class="footnote">...</div>` is interpreted as `<p>...</p><div class="footnote">...</div>`. This is the reason of "Footnote call broke off as a new paragraph".

See the HTML spec:
https://html.spec.whatwg.org/#the-p-element

> 4.4.1 The p element
> …
> Content model: Phrasing content.
>
> Tag omission in text/html:
> A p element's end tag can be omitted if the p element is immediately followed by an address, article, aside, blockquote, details, div, dl, fieldset, figcaption, figure, footer, form, h1, h2, h3, h4, h5, h6, header, hgroup, hr, main, menu, nav, ol, p, pre, search, section, table, or ul element, or if there is no more content in the parent element and the parent element is an HTML element that is not an a, audio, del, ins, map, noscript, or video element, or an autonomous custom element.


A workaround will be: use `<span class="footnote">` for footnotes and `<span class="p">` for paragraphs inside footnotes. Example:

```css
.p {
    display: block;
    margin: 1em 0;
}

.footnote { 
    float: footnote; 
}
```

```html
<p>Though the body was erect, the head was thrown back so that the
closed eyes were pointed towards the needle of the tell-tale that swung
from a beam in the ceiling.<span class="footnote">
    <span class="p">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent varius velit nibh, tristique sollicitudin dolor malesuada eu. Pellentesque non fermentum ex. Phasellus et posuere tortor, fringilla malesuada diam. Duis purus enim, ullamcorper nec risus id, pulvinar consequat velit. Morbi ullamcorper libero sit amet nunc pellentesque rhoncus. Mauris sed nulla vel turpis feugiat elementum. Praesent consectetur, leo et posuere luctus, ligula ipsum dapibus lacus, eu porta felis ante nec ex. Aliquam erat volutpat. Vestibulum auctor odio lorem, consequat hendrerit felis feugiat sit amet. Duis tempus erat nec fermentum bibendum. Sed porttitor odio orci, in aliquet odio vulputate non. Sed eget quam et libero bibendum congue. In ornare metus massa, et semper ipsum ultrices ut.</span>
    <span class="p">Nunc sapien ligula, accumsan ac velit ac, congue iaculis eros. Etiam varius, quam at bibendum commodo, magna lorem rutrum velit, a laoreet nulla ante ac lorem. Suspendisse potenti. Vestibulum justo urna, porta ut libero vitae, luctus efficitur nisi. Integer egestas metus id elementum lacinia. Sed a odio at augue malesuada luctus. Nunc ullamcorper purus et ipsum scelerisque, id molestie diam lacinia.</span>
    <span>Proin eu congue elit. Sed ut magna nec elit lacinia facilisis. Sed ornare, dui vitae iaculis fringilla, diam odio mattis augue, ac congue augue neque in nisl. Nullam sollicitudin eu dolor cursus gravida. Nunc non consectetur velit. Suspendisse potenti. Sed gravida laoreet enim, ac eleifend felis vehicula eget. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec faucibus tellus a ligula placerat, sit amet fermentum nisi ultrices. Phasellus pharetra, tortor quis dapibus ultrices, nulla lorem venenatis eros, et imperdiet nisl felis non dolor.</span>
</span>
The cabin-compass is called the tell-tale, because without going to the compass at the helm, the Captain, while below, can inform himself of the course of the ship.
</p>
<p>Though the body was erect, the head was thrown back so that the
closed eyes were pointed towards the needle of the tell-tale that swung
from a beam in the ceiling.<span class="footnote">
    <span class="p">Nam auctor non eros vel consectetur. Curabitur risus leo, varius sed leo ut, sagittis bibendum lectus. Sed sed placerat neque, at pharetra orci. Nulla nec condimentum sapien, in feugiat tortor. Aenean suscipit, elit at aliquam ultricies, ligula libero pretium turpis, at sagittis ex velit eget nulla. Curabitur blandit odio nulla, quis porttitor elit fermentum placerat. Duis quis nunc quis felis fermentum scelerisque eget ut mauris. Aenean id euismod ipsum. Vestibulum posuere augue eget nulla feugiat, nec pharetra sapien pellentesque. Etiam vitae massa vitae dui lacinia dapibus. Nulla sodales lectus id tempus tincidunt. Cras sed rhoncus nunc. Aenean laoreet varius sapien sed interdum. Fusce pharetra mauris sed tortor tincidunt aliquam. Maecenas sodales, sapien id interdum faucibus, diam urna semper enim, sed pharetra ante nibh at lorem. Donec pretium ante velit, non commodo lacus efficitur vitae.</span>
    <span class="p">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus auctor ante quis odio elementum, ac aliquam purus faucibus. Quisque ultrices risus at gravida consectetur. Quisque molestie, dolor cursus placerat blandit, quam est tincidunt ex, at dapibus dolor metus ac lorem. Proin ut mauris erat. Maecenas auctor augue leo, ac tempus metus convallis a. Nullam dapibus, augue nec blandit varius, ipsum nisi dignissim libero, a faucibus lectus sapien id risus. Duis justo diam, elementum in elit id, consectetur porta nunc. Fusce convallis nibh sed mattis semper.</span>
</span>
</p>
```

**Comment by eudoxos** [comment]
Thank you, @MurakamiShinyu, I understand now that HTML parser had to break the document flow. I updated the example; it is somewhat convolved since the first paragraph of the footnote must go into the same paragraph with the footnote marker, but otherwise it looks at least usable. Below the output from Vivliostyle and Weasyprint.
image

**Comment by MurakamiShinyu** [comment]
FYI, Vivliostyle has an issue that the `@footnote` rule is unsupported. See: 
- https://github.com/vivliostyle/vivliostyle.js/issues/1045

**Comment by zopyx** [comment]
moved to incubator `in-progress` directory

**Pull request merged**
